language: bash
services: docker
before_install:
  - cd WorkspaceSpringBoot/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push 740fernando/mysql-rest-with-spring-boot
    docker push 740fernando/rest-with-spring-boot
  on:
    branch: master
notifications:
  email: false