version: '3.4;
services:
  db:
    image: 740fernando/mysql-rest-with-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest-with-spring-boot
    ports:
      - "3308:3308"
    networks:
      - ntt-network
  rest-with-spring-boot:
    image: 740fernando/rest-with-spring-boot
    restart: always
    build: ./rest-with-springboot
    work_dir: ./rest-with-springboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./rest-with-springboot: /rest-with-springboot
      - ~/.m2: /root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - ntt-network
networks:
    ntt-network:
          driver: bridge